### ISSUE TITLE
Fails to parse exponents with a decimal component.

### ISSUE THREAD

**Issue by leesdolphin** [RazrFalcon/libsvgparser#4]
I was debugging some issues I was having and traced the issue back to using `1.2e3` in an SVG number component. The [SVG Number](https://www.w3.org/TR/SVG/types.html#DataTypeNumber) data type indicates that it should support numbers of this kind.

For example, this file should parse correctly, however it fails to parse the `translate` transformation, and it also fails to parse the `path` definition beyond the first invalid exponent:

```
<svg>
  <g transform="translate(11,2.5e-4)">
    <path
       d="m 1,2.2e-4 10,10 -10,10"
    />
  </g>
</svg>
```

Ideally this should be equivalent to 
```
<svg>
  <g transform="translate(11,0.00025)">
    <path
       d="m 1,0.00022 10,10 -10,10"
    />
  </g>
</svg>
```

**Comment by RazrFalcon** [comment]
Yes. Looks like I broke it few commits ago.
