### ISSUE TITLE
Implementing Iterator for Tokenizer

### ISSUE THREAD

**Issue by dbrgn** [RazrFalcon/libsvgparser#7]
Would it be possible to make a `Tokenizer` an [Iterator](https://doc.rust-lang.org/std/iter/trait.Iterator.html), so that parsing could be done with

```rust
for token in tokenizer {
...
}
```

instead of

```rust
loop {
  match tokenizer.parse_next() {
    ...
  }
}
```

?

Since the `next()` method of an iterator can only return an `Option`, not a `Result`, the return type would probably have to be `Option<Result<Token>>`.

I'm not sure how `EndOfStream` would need to be handled in that case though. It's a bit of a Meta-Token, since it doesn't correspond to "real" data. It would be obsolete by returning `None` from `next()`.

Or are there any downsides to that approach? There might be a good reason why you chose `parse_next()` :)

**Comment by RazrFalcon** [comment]
Yes. I thought about it, but the main downside is that it will be the same, because you have to unwrap the result, so:

```rust
for token in tokenizer {
    let token = token?;
...
}
```

**Comment by dbrgn** [comment]
The main advantage is that you don't have to check for `EndOfStream` and then break the infinite loop. That's a bit unintuitive to me.

**Comment by RazrFalcon** [comment]
Also you will be able to use filter/map/etc. 

Sounds reasonable. Will add it soon.

PS: it was actually implemented in older version, but badly, so I removed it.

**Comment by dbrgn** [comment]
> Also you will be able to use filter/map/etc.

That sounds like a *very* good idea :)

**Comment by RazrFalcon** [comment]
Done in 0.5

See [`Tokenize::tokens`](https://docs.rs/svgparser/0.5.0/svgparser/trait.Tokenize.html#method.tokens) documentation and [examples/parser.rs](https://github.com/RazrFalcon/libsvgparser/blob/master/examples/parser.rs) for details.
