### ISSUE TITLE
Parsing only certain objects

### ISSUE THREAD

**Issue by dbrgn** [RazrFalcon/libsvgparser#8]
I want to convert SVG paths to polylines (see https://github.com/dbrgn/svg2polylines). For that, I only need to parse the `d` attributes of `path` elements (at least for now).

Right now the tokenizer loops over all tokens, which are all elements and attributes.

It would be interesting if there were a way to filter the types of tokens that are tokenized. For example, first I'd only want to tokenize elements (filtering for `Token::SvgElementStart` elements). If I encounter an `ElementId::Path`, I'd then drill down and iterate over all attributes of that element.

I hope that description is clear enough (if not, just ask for clarification). I'm not sure how the parser is implemented internally, so this might be easy or hard to do. Also, an event base (SAX style) parser might be better suited for my use case, but I don't really have much experience with those.

(If this is out of scope, feel free to close the issue 🙂)

**Comment by RazrFalcon** [comment]
>an event base (SAX style) parser might be better suited for my use case
This is event based parser.

As far as I understand you want to get rid of the Attribute event and use, for example, `attributes()` method when you needed? It doesn't supported right now.

If you want to skip parsing completely - this is impossible, since I must iterate over each byte/char, because the input can be malformed.

**Comment by dbrgn** [comment]
> If you want to skip parsing completely - this is impossible, since I must iterate over each byte/char, because the input can be malformed.

Yeah, that's true. Not returning tokens for certain attributes would probably give us very little added performance.

In that case I'll close this issue again.
